import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LocalizationProvider with ChangeNotifier {
  String _currentLanguage = 'uz'; // Standart til (O'zbekcha)

  String get currentLanguage => _currentLanguage;

  final Map<String, Map<String, String>> _localizedStrings = {
    'uz': {
      'savatga': 'Savatga',
      'otish': "O'tish",
      'savatga_qoshish': "Savatga qo'shish",
      'savatga_qoshildi': "Savatga qo'shildi",
      'narxi': 'NARXI',
      'malumot': "Ma'lumot",
      'asosiy': 'Asosiy',
      'katalog': 'Katalog',
      'savat': 'Savat',
      'buyurtmalarim': 'Buyurtmalarim',
      'profil': 'Profil',
      'chegirma': 'CHEGIRMA',
      'tasdiqlash': 'Tasdiqlash',
      'buyurtma_berish': 'Buyurtma berish',
      'tilni_tanlang': 'Tilni tanlang',
      'davom_etish': 'Davom etish',
      'tizimdan_chiqish': 'Tizimdan chiqish',

      // --- About Screen ---
      'versiya': 'Versiya',
      'about_desc': "Eng tezkor va ishonchli onlayn supermarket! Uyingizgacha eng sifatli mahsulotlarni bir zumda yetkazib beramiz.",
      'faq_title': "Ko'p beriladigan savollar",
      'faq_q1': "Yetkazib berish xizmati qancha vaqt oladi?",
      'faq_a1': "Raketa Market xizmati o'z nomiga munosib tarzda buyurtmangizni 15-30 daqiqa ichida uyingizga yetkazib beradi.",
      'faq_q2': "To'lovni qanday usullarda amalga oshirish mumkin?",
      'faq_a2': "Naqd pul, shuningdek, uzcard yoki humo plastik kartalari orqali to'g'ridan-to'g'ri to'lashingiz mumkin.",
      'faq_q3': "Buyurtmani bekor qilish mumkinmi?",
      'faq_a3': "Buyurtmangiz dastavka bo'limiga o'tmasdan bemalol bekor qila olasiz.",
      'faq_q4': "Profil ma'lumotlarini qanday o'zgartirish mumkin?",
      'faq_a4': "Profil bo'limiga o'tib, 'Shaxsiy ma'lumotlar' qismida ismingiz, jinsingiz va boshqa ma'lumotlarni tahrirlashingiz mumkin.",
      'faq_q5': "Mahsulot sifatsiz chiqsa nima bo'ladi?",
      'faq_a5': "Biz sifatga kafolat beramiz. Agar mahsulot sifati yoqmasa, yetkazib beruvchi (kuryer) orqali rad etishingiz mumkin, shunda summangiz olib qolinmaydi.",

      // --- Support & Profile Edit ---
      'support_title': "Qo'llab-quvvatlash",
      'support_question': "Biz bilan qanday bog'lanmoqchisiz?",
      'support_desc': "Savol va takliflaringiz bo'lsa bizga yozing yoki qo'ng'iroq qiling.",
      'support_cancel': "Bekor qilish",
      'via_telegram': "Telegram orqali",
      'telegram_desc': "Tez yozish va javob olish",
      'send_msg': "Xabar yozish",
      'via_phone': "Qo'ng'iroq qilish",
      'phone_desc': "Aloqa markaziga bog'lanish",
      'redirecting': "Ilovaga yo'naltirilmoqda...",
      'personal_info': "Shaxsiy ma'lumotlar",
      'name_label': "Manzil nomi",
      'name_hint': "Ismingizni kiriting",
      'surname_label': "Familiya",
      'surname_hint': "Familiyangizni kiriting",
      'dob_label': "Tug'ilgan sana",
      'gender_label': "Jins",
      'male': "Erkak",
      'female': "Ayol",
      'phone_label': "Telefon raqam",
      'email_label': "E-mail manzil",
      'email_hint': "namuna@mail.com",
      'save_button': "Saqlash",
      'del_acc': "Akkauntni butunlay o'chirish",
      'del_acc_title': "Akkauntni o'chirish",
      'del_acc_desc': "Akkauntingizni umrbod o'chirib tashlamoqchimisiz? Barcha ma'lumotlaringiz va tarixingiz butunlay o'chiriladi.",
      'del_acc_btn': "O'chirish",
      'confirm_number': "Raqamni tasdiqlash",
      'enter_sms': "Yangi raqamingizga yuborilgan SMS kodni kiriting",
      'verify_btn': "Tasdiqlash",
      'data_saved': "Ma'lumotlar muvaffaqiyatli saqlandi!",
      'acc_deleted': "Akkaunt muvaffaqiyatli o'chirildi",
      
      // --- Addresses Screen ---
      'my_address': 'Mening manzilim',
      'region_select_title': 'Viloyatni tanlang',
      'district_select_title': 'Tuman (shahar)ni tanlang',
      'your_region': 'Hududingiz:',
      'select_region_hint': 'Viloyatni tanlang',
      'add_address_prompt': "Manzilingizni kiritish uchun \ndastlab viloyatni tanlang",
      'sorry': 'Kechirasiz!',
      'no_service': "Hozircha ushbu hududda xizmatimiz yo'q. Ammo tez orada albatta yetib boramiz!",
      'address_details': 'Manzil tafsilotlari:',
      'region_label': 'Viloyat',
      'district_label': 'Tuman',
      'street_label': "Ko'cha",
      'house_label': 'Uy',
      'house_hint': 'Masalan: 45-uy, 12-xonadon',
      'pick_map': 'Xaritadan belgilash',
      'fill_all': "Iltimos, barcha maydonlarni to'ldiring",
      'address_saved': 'Manzilingiz saqlandi!',
      'map_open_warning': 'Xaritadan joylashuv tanlash ochiladi',
      'add_new_address': "Yangi manzil qo'shish",
      'address_title_label': "Manzil nomi (Masalan: Uy, Ish)",
      'address_title_hint': "Manzilga nom bering",
      'set_as_default': "Asosiy manzil sifatida belgilash",
      'delete_address_confirm': "Haqiqatan ham ushbu manzilni o'chirmoqchimisiz?",
      'no_addresses_yet': "Hozircha manzillar yo'q. Yangi manzil qo'shing!",
      'default_label': "Asosiy",
      'save_address': "Manzilni saqlash",
      'select_within': "Iltimos,",
      'area': "hududidan tanlang",
      'loading': "Yuklanmoqda...",
      'coordinates': "Koordinatalar",
      'search_on_map': "Manzilni xaritadan tanlang",
      'region_not_active': "Hali bu yerda yo'qmiz",
      'gps_disabled': "GPS o'chirilgan",
      'location_permission_denied': "Joylashuvga ruxsat berilmadi",
      'unable_to_determine_location': "Joylashuvni aniqlab bo'lmadi",
      'understand': "Tushunarli",
      'get_directions': "Yo'nalishni boshlash",
      'pickup_at_main_store': 'Samovivoz (Asosiy do\'kon)',
      'promo_info_title': 'Promo kod haqida ma\'lumot',
      'promo_eligibility_note': 'Promo kod faqat chegirmasiz mahsulotlar uchun amal qiladi.',
      'promo_info_text_main': 'Promo kod yetkazib berish xizmati yoki mahsulotlar uchun amal qilinganda jami savatdagi chegirmali mahsulotlarni hisobga olmaydi.',
      'promo_info_text_important': "Muhim: Mahsulotlar uchun PROMO KOD faqat do'kon tomonidan hali chegirma berilmagan (chegirmasiz) mahsulotlar uchun amal qiladi. Promo kod ishlashi uchun savatingizda yetarli miqdorda chegirmasiz mahsulotlar bo'lishi shart.",
      'view_products_list': 'Mahsulotlar ro\'yxatini ko\'rish',
      'discounted_products': "Chegirmalik mahsulotlar",
      'non_discounted_products': "Chegirmasiz mahsulotlar",

      // --- Checkout Screen Details ---
      'checkout': 'Rasmiylashtirish',
      'contact_info': 'Aloqa ma\'lumotlari',
      'full_name': 'Ism va familiya',
      'phone_number': 'Telefon raqam',
      'receive_method': 'Qabul qilish usuli',
      'delivery': 'Yetkazib berish (Dastavka)',
      'pickup': 'Borib olib ketish (Tez kunda)',
      'your_address': 'Manzilingiz',
      'searching_address': 'Manzil qidirilmoqda...',
      'unknown_area': 'Noaniq hudud',
      'cannot_determine_address': 'Manzilni aniqlab bo\'lmadi',
      'connection_error': 'Ulanishda xatolik',
      'courier_desc': 'Kuryer uchun tavsif',
      'courier_desc_hint': 'Masalan: uy raqami, podyezd va h.k.',
      'store_address': 'Do\'kon manzili',
      'raketa_main_branch': 'Raketa Market (Asosiy filial)',
      'store_address_detail': 'Toshkent sh., Yunusobod tumani, 4-mavze, 12-uy',
      'start_routing': 'Yo\'nalishni boshlash',
      'payment_type': 'To\'lov turi',
      'cash_payment': 'Naqd pul orqali',
      'card_payment': 'Karta orqali',
      'coming_soon': 'Tez kunda',
      'card_number': 'Karta raqami',
      'expire_date': 'Muddati',
      'charge_payment': 'To\'lovni yechish',
      'promo_code': 'Promo kod',
      'enter_promo': 'Promo kodni kiriting',
      'apply': 'Qo\'llash',
      'promo_applied': 'Promo kod qo\'llanildi!',
      'wrong_promo': 'Noto\'g\'ri promo kod',
      'promo_not_found': 'Promo kod topilmadi yoki muddati o\'tgan',
      'promo_missing_amount_error': 'Yana %s so\'mlik chegirmasiz mahsulot qo\'shing',
      'promo_min_amount_error': 'Chegirmasiz mahsulotlar summasi kamida %s so\'m bo\'lishi kerak',
      'promo_total_limit_reached': 'Kechirasiz, promo kod limiti tugagan',
      'promo_user_limit_reached': 'Siz bu koddan foydalanib bo\'lgansiz',
      'promo_eligible_error': 'Kechirasiz, bu promo-kod faqat chegirmasiz mahsulotlar uchun amal qiladi (savatingizda yetarli chegirmasiz mahsulotlar yo\'q)',
      'promo_system_error': 'Tizimda xatolik yuz berdi. Keyinroq urinib ko\'ring',
      'chegirma_berildi': 'Sizga %s so\'m chegirma berildi',
      'products_label': 'Mahsulotlar:',
      'delivery_fee': 'Yetkazib berish:',
      'free': 'Bepul',
      'discount_label': 'Chegirma:',
      'total_amount_checkout': 'Jami summa:',
      'fill_name_phone': 'Iltimos, ism va telefoningizni kiriting',
      'checkout_success': 'Muvaffaqiyatli rasmiylashtirdingiz!',
      'checkout_error': 'Xatolik yuz berdi. Iltimos qaytadan urinib ko\'ring.',
      'confirm_order': 'Buyurtmani tasdiqlash',
      'delivery_promo_free': 'Yana %s %s xarid qiling va bepul yetkazib berishga ega bo\'ling!',
      'delivery_promo_tier': 'Yana %s %s xarid qiling va yetkazib berish narxini %s %sga tushiring!',

      // --- Login & SMS Screens ---
      'login_title': 'Tizimga kirish',
      'login_desc_phone': 'Ilovaga kirish uchun telefon raqamingizni kiriting va SMS kod orqali tasdiqlang',
      'login_desc_full': 'Ilovadan to\'liq foydalanish va xarid qilish uchun to\'liq ismingiz hamda telefon raqamingizni kiriting',
      'login_name_label': 'Ism va Familiya',
      'login_phone_label': 'Telefon raqam',
      'please_enter_name': 'Iltimos, ismingizni kiriting',
      'please_enter_phone_full': 'Telefon raqamini to\'liq kiriting',
      'phone_exists_error': 'Bu raqam tizimda mavjud. Iltimos "Tizimda borman" tugmasini bosing.',
      'phone_not_exists_error': 'Bu raqam tizimda mavjud emas. Iltimos ro\'yxatdan o\'ting.',
      'get_code_button': 'Kodni olish',
      'create_new_account': 'Yangi akkaunt yaratish',
      'already_in_system': 'Tizimda borman',
      'sms_title': 'Tasdiqlash',
      'sms_desc': 'Siz kiritgan raqamga tasdiqlash kodi yuborildi. Iltimos, kodni kiriting.',

      // --- Onboarding Screen ---
      'onboarding_title_1': 'Barcha kerakli narsalar',
      'onboarding_desc_1': 'Oziq-ovqatdan tortib uy ro\'zg\'or buyumlarigacha barchasi bitta ilovada',
      'onboarding_title_2': 'Tezkor Yetkazib Berish',
      'onboarding_desc_2': 'Buyurtmangiz uyingizgacha tez va ishonchli yetkazib beriladi',
      'onboarding_title_3': 'Ajoyib Chegirmalar',
      'onboarding_desc_3': 'Har kuni yangi aksiyalar va skidkalar faqat siz uchun',
      'onboarding_start': 'Boshlash',
      'onboarding_next': 'Keyingi',

      // --- Checkout & Orders ---
      'chiqish_tasdiq': 'Haqiqatan ham akkauntingizdan chiqmoqchimisiz?',
      'bekor_qilish': 'Bekor qilish',
      'chiqish': 'Chiqish',
      'mening_manzilim': 'Mening manzilim',
      'ilova_tili': 'Ilova tili',
      'tungi_rejim': 'Tungi rejim',
      'qollab_quvvatlash': "Qo'llab-quvvatlash",
      'ilova_haqida': 'Ilova haqida',
      'ilova_tilini_tanlang': 'Ilova tilini tanlang',
      'savatingiz_bosh': "Savatingiz bo'sh",
      'xaridni_boshlash': 'Xaridni boshlash',
      'xaridga_qoshilgan': "Xaridga qo'shilgan",
      'keyinchalikka_qoldirildi': 'Keyinchalikka qoldirildi',
      'jami_summa': 'Jami summa:',
      'savatda_yetarli_mahsulot_yoq': "Savatda yetarli mahsulot yo'q!",
      'rasmiylashtirish': 'Rasmiylashtirish',
      'hozircha_buyurtmalar_yoq': "Hozircha buyurtmalar yo'q",
      'sana': 'Sana:',
      'buyurtma_id': 'Buyurtma ID:',
      'jami': 'JAMI:',
      'yangi_tab': 'Yangi',
      'yetkazilgan_tab': 'Yetkazib berilgan',
      'hammasi_tab': 'Hammasi',
      'jarayonda': 'Jarayonda',
      'yetkazilgan': 'Yetkazilgan',
      'mahsulot': 'mahsulot',
      'buyurtma': 'Buyurtma',
      'buyurtma_jarayoni': 'Buyurtma jarayoni',
      'qabul_kutilmoqda': 'Qabul qilish kutilmoqda',
      'tayyorlanmoqda': 'Tayyorlanmoqda',
      'yetkazilmoqda': 'Yetkazilmoqda',
      'yetkazildi': 'Yetkazildi',
      'mijoz_malumotlari': "Mijoz ma'lumotlari",
      'fish': 'F.I.SH:',
      'telefon': 'Telefon:',
      'manzil': 'Manzil:',
      'tolov_usuli': "To'lov usuli:",
      'xarid_qilingan_mahsulotlar': 'Xarid qilingan mahsulotlar',
      'dona': 'dona',
      'tasdiqlash_kodi': 'Tasdiqlash kodi',
      'kuryer_ogohlantirish': "Kodni kuryerga yetib kelganda aytishingiz kerak. Kod orqali buyurtma yopiladi.",
      'qidirish': 'Qidirish...',
      'hech_narsa_topilmadi': 'Hech narsa topilmadi',
      'qidiruv_tarixini_boshlang': 'Qidiruv tarixini boshlang',
      'qidiruv_tarixi': 'Qidiruv tarixi',
      'katalogdan_qidirish': 'Katalogdan qidirish...',
      'bolimidan_qidirish': "bo'limidan qidirish",
      'hozircha_malumot_yoq': "Hozircha ma'lumot yo'q",
      'kategoriyalar': 'Kategoriyalar',
      'yangi_maxsulotlar': 'Yangi maxsulotlar',
      'maxsulotlar': 'Maxsulotlar',
      'natija': 'Natija',
      'you_might_like': 'Sizga yoqishi mumkin',
      'qulay_tezkor': 'Qulay, tezkor va arzon narxlar',
      'tilni_ozgartirish': "Tilni o'zgartirish",
      'kunduzgi_rejim': 'Kunduzgi rejim',
      'mahsulot_toifa_qidirish': 'Mahsulot va toifalarni qidirish',
      'aksiya_1': 'Aksiya 1',
      'aksiya_1_subtitle': '-50% Chegirma',
      'yangi_maxsulotlar_subtitle': "Birinchi bo'lib tatib ko'ring",
      'bepul_yetkazish': 'Bepul Yetkazish',
      'bepul_yetkazish_subtitle': "100,000 so'm va undan yuqori xaridlar uchun",
      'Chegirma': 'Chegirma',
      'Oziq-ovqat': 'Oziq-ovqat',
      'Ichimliklar': 'Ichimliklar',
      'Shirinliklar': 'Shirinliklar',
      'Mevalar': 'Mevalar',
      'Sabzavotlar': 'Sabzavotlar',
      "Go'sht": "Go'sht",
      'Sut mahsulotilari': 'Sut mahsulotlari',
      'Non va un': 'Non va un',
      'Maishiy kimyo': 'Maishiy kimyo',
      'Bolalar oziq-ovqati': 'Bolalar oziq-ovqati',
      "Go'zallik": "Go'zallik",
      'Uy hayvonlari': 'Uy hayvonlari',
      'buyurtma_no': 'Buyurtma №:',
      'buyurtma_id_title': 'Buyurtma ID:',
      'yuboruvchi': 'Yuboruvchi:',
      'oluvchi': 'Oluvchi:',
      'mahsulotlar_soni': 'Mahsulotlar soni:',
      'telefon_raqami': 'Telefon raqami:',
      'som': "so'm",
      'ta_dona': 'ta',
      'mahsulotni_korish': "Mahsulotni ko'rish",
      'buyurtma_raq_id': "Buyurtma raqami / ID:",
      'kuryerga_tolov': 'Kuryerga',
      'sana_va_vaqt': 'Sana va vaqt:',
      'kuryerga_izoh': 'Kuryerga izoh:',
      'order_delivered_title': 'Buyurtma yetkazildi',
      'order_cancelled_title': 'Buyurtma bekor qilingan',
      'order_process_title': 'Buyurtmam qaysi jarayonda:',
      'order_cancelled': 'Buyurtma bekor qilindi',
      'error': 'Xatolik',
      'cancel_order_btn': 'Buyurtmani bekor qilish',
      'cancel_warning_desc': "Siz buyurtmani qabul qilinishidan oldin va tayyorlanish jarayonigacha bemalol bekor qilishingiz mumkin. Ammo buyurtma 'Tayyor' bo'lib kuryerga o'tgandan so'ng bekor qilib bo'lmaydi!",
      'Qabul qilingan': 'Qabul qilingan',
      'Qabul qilish kutilmoqda': 'Qabul qilish kutilmoqda',
      'Qabul qilinishi kutilmoqda': 'Qabul qilinishi kutilmoqda',
      'Tayyor': 'Tayyor',
      'Tayyorlanmoqda': 'Tayyorlanmoqda',
      "Yo'lda": "Yo'lda",
      'Kuryer kutilmoqda': 'Kuryer kutilmoqda',
      'Kuryerga berildi': 'Kuryerga berildi',
      'Yetkazildi': 'Yetkazildi',
      'chegirmalik_badge': 'Chegirmalik',
      'cancelled_badge': 'Bekor qilindi',
      'hisob_kitob': 'Hisob-kitob',
      'umumiy_mahsulot_narxi': 'Umumiy mahsulot narxi:',
      'yetkazib_berish_title': 'Yetkazib berish:',
      'bepul': 'Bepul',
      'promo_kod_chegirma': 'Promo kod (Chegirma):',
      'yoq': "Yo'q",
      'mahsulotlar': 'Mahsulotlar',
      'buyurtma_tafsilotlari': 'Buyurtma tafsilotlari',
      'sevimlilar': 'Sevimlilar',
      'sevimlilar_bosh': 'Sevimlilar bo\'sh',
      'bizning_dokonlarimiz': "Bizning do'konlarimiz",
      'announcements': "E'lonlar",
      'no_announcements': "Hozircha e'lonlar yo'q",
      'january': 'Yanvar',
      'february': 'Fevral',
      'march': 'Mart',
      'april': 'Aprel',
      'may_month': 'May',
      'june': 'Iyun',
      'july': 'Iyul',
      'august': 'Avgust',
      'september': 'Sentabr',
      'october': 'Oktabr',
      'november': 'Noyabr',
      'december': 'Dekabr',
    },
    'ru': {
      'savatga': 'В корзину',
      'otish': 'Перейти',
      'savatga_qoshish': 'В корзину',
      'savatga_qoshildi': 'Добавлено в корзину',
      'narxi': 'ЦЕНА',
      'malumot': 'Информация',
      'asosiy': 'Главная',
      'katalog': 'Каталог',
      'savat': 'Корзина',
      'buyurtmalarim': 'Мои заказы',
      'profil': 'Профиль',
      'chegirma': 'СКИДКА',
      'tasdiqlash': 'Подтвердить',
      'buyurtma_berish': 'Оформить заказ',
      'tilni_tanlang': 'Выберите язык',
      'davom_etish': 'Продолжить',
      'tizimdan_chiqish': 'Выйти из системы',

      // --- About Screen ---
      'versiya': 'Версия',
      'about_desc': "Самый быстрый и надежный онлайн-супермаркет! Мы мгновенно доставим самые качественные продукты прямо к вашей двери.",
      'faq_title': "Часто задаваемые вопросы",
      'faq_q1': "Сколько времени занимает доставка?",
      'faq_a1': "Служба Raketa Market оправдывает свое название, доставляя ваш заказ за 15-30 минут.",
      'faq_q2': "Какими способами можно совершить оплату?",
      'faq_a2': "Вы можете оплатить наличными, а также напрямую картами uzcard или humo.",
      'faq_q3': "Можно ли отменить заказ?",
      'faq_a3': "Вы можете легко отменить свой заказ, прежде чем он перейдет в стадию доставки.",
      'faq_q4': "Как изменить данные профиля?",
      'faq_a4': "Перейдите в раздел профиля и в разделе 'Личная информация' вы можете отредактировать свое имя, пол и другие данные.",
      'faq_q5': "Что произойдет, если продукт бракованный?",
      'faq_a5': "Мы гарантируем качество. Если вам не нравится качество товара, вы можете отказаться от него через курьера, и ваши деньги не удержатся.",

      // --- Support & Profile Edit ---
      'support_title': "Служба поддержки",
      'support_question': "Как вы хотите связаться с нами?",
      'support_desc': "Если у вас есть вопросы или предложения, напишите или позвоните нам.",
      'support_cancel': "Отмена",
      'via_telegram': "Через Telegram",
      'telegram_desc': "Быстрое сообщение и ответ",
      'send_msg': "Написать сообщение",
      'via_phone': "Позвонить",
      'phone_desc': "Связаться с колл-центром",
      'redirecting': "Перенаправление...",
      'personal_info': "Личная информация",
      'name_label': "Название адреса",
      'name_hint': "Введите ваше имя",
      'surname_label': "Фамилия",
      'surname_hint': "Введите вашу фамилию",
      'dob_label': "Дата рождения",
      'gender_label': "Пол",
      'male': "Мужской",
      'female': "Женский",
      'phone_label': "Номер телефона",
      'email_label': "Электронная почта",
      'email_hint': "пример@mail.com",
      'save_button': "Сохранить",
      'del_acc': "Удалить аккаунт навсегда",
      'del_acc_title': "Удаление аккаунта",
      'del_acc_desc': "Вы собираетесь навсегда удалить свой аккаунт. Все ваши данные и история будут стерты безвозвратно.",
      'del_acc_btn': "Удалить",
      'confirm_number': "Подтверждение номера",
      'enter_sms': "Введите SMS код, отправленный на новый номер",
      'verify_btn': "Подтвердить",
      'data_saved': "Данные успешно сохранены!",
      'acc_deleted': "Аккаунт успешно удален",

      // --- Addresses Screen ---
      'my_address': 'Мой адрес',
      'region_select_title': 'Выберите область',
      'district_select_title': 'Выберите район (город)',
      'your_region': 'Ваш регион:',
      'select_region_hint': 'Выберите область',
      'add_address_prompt': "Сначала выберите область,\nчтобы ввести свой адрес",
      'sorry': 'Извините! 😔',
      'no_service': "В выбранном регионе наш сервис пока не работает. Но скоро мы обязательно придем!",
      'address_details': 'Детали адреса:',
      'region_label': 'Область',
      'district_label': 'Район',
      'street_label': "Улица",
      'house_label': 'Дом',
      'house_hint': 'Например: дом 45, квартира 12',
      'pick_map': 'Указать на карте',
      'fill_all': "Пожалуйста, заполните все поля",
      'address_saved': 'Ваш адрес сохранен!',
      'map_open_warning': 'Откроется выбор местоположения на карте',
      'add_new_address': "Добавить новый адрес",
      'address_title_label': "Название адреса (Например: Дом, Работа)",
      'address_title_hint': "Дайте название адресу",
      'set_as_default': "Установить как основной адрес",
      'delete_address_confirm': "Вы действительно хотите удалить этот адрес?",
      'no_addresses_yet': "Адресов пока нет. Добавьте новый адрес!",
      'default_label': "Основной",
      'save_address': "Сохранить адрес",
      'select_within': "Пожалуйста, выберите в пределах",
      'area': "",
      'loading': "Загрузка...",
      'coordinates': "Координаты",
      'search_on_map': "Выберите адрес на карте",
      'region_not_active': "Нас здесь пока нет",
      'gps_disabled': "GPS отключен",
      'location_permission_denied': "Доступ к местоположению запрещен",
      'unable_to_determine_location': "Не удалось определить местоположение",
      'understand': "Понятно",
      'get_directions': "Проложить маршрут",
      'pickup_at_main_store': 'Самовывоз (Главный магазин)',
      'promo_info_title': 'Информация о промокоде',
      'promo_eligibility_note': 'Промокод действует только на товары без скидки (не с желтой ценой).',
      'promo_info_text_main': 'При применении промокода к службе доставки или товарам, сумма товаров со скидкой не учитывается.',
      'promo_info_text_important': 'Важно: ПРОМОКОД на товары распространяется только на те товары, на которые еще не установлена скидка магазином (товары без скидки). Для работы промокода в корзине должно быть достаточно товаров без скидки.',
      'view_products_list': 'Посмотреть список товаров',
      'discounted_products': "Товары со скидкой",
      'non_discounted_products': "Товары без скидки",

      // --- Checkout Screen Details ---
      'checkout': 'Оформление заказа',
      'contact_info': 'Контактная информация',
      'full_name': 'Имя и фамилия',
      'phone_number': 'Номер телефона',
      'receive_method': 'Способ получения',
      'delivery': 'Доставка',
      'pickup': 'Самовывоз (Скоро)',
      'your_address': 'Ваш адрес',
      'searching_address': 'Поиск адреса...',
      'unknown_area': 'Неизвестная зона',
      'cannot_determine_address': 'Не удалось определить адрес',
      'connection_error': 'Ошибка подключения',
      'courier_desc': 'Описание для курьера',
      'courier_desc_hint': 'Например: номер дома, подъезд и т.д.',
      'store_address': 'Адрес магазина',
      'raketa_main_branch': 'Raketa Market (Главный филиал)',
      'store_address_detail': 'г. Ташкент, Юнусабадский район, 4-й квартал, дом 12',
      'start_routing': 'Начать маршрут',
      'payment_type': 'Тип оплаты',
      'cash_payment': 'Наличными',
      'card_payment': 'Картой',
      'coming_soon': 'Скоро',
      'card_number': 'Номер карты',
      'expire_date': 'Срок действия',
      'charge_payment': 'Снять оплату',
      'promo_code': 'Промокод',
      'enter_promo': 'Введите промокод',
      'apply': 'Применить',
      'promo_applied': 'Промокод применен!',
      'wrong_promo': 'Неверный промокод',
      'promo_not_found': 'Промокод не найден или срок действия истек',
      'promo_missing_amount_error': 'Добавьте еще товаров без скидки на %s сум',
      'promo_min_amount_error': 'Сумма товаров без скидки должна быть не менее %s сум',
      'promo_total_limit_reached': 'К сожалению, лимит промокода исчерпан',
      'promo_user_limit_reached': 'Вы уже использовали этот промокод',
      'promo_eligible_error': 'Извините, этот промокод действует только на товары без скидки (в вашей корзине недостаточно таких товаров)',
      'promo_system_error': 'Произошла системная ошибка. Попробуйте позже',
      'chegirma_berildi': 'Вам предоставлена скидка %s сум',
      'products_label': 'Товары:',
      'delivery_fee': 'Доставка:',
      'free': 'Бесплатно',
      'discount_label': 'Скидка:',
      'total_amount_checkout': 'Общая сумма:',
      'fill_name_phone': 'Пожалуйста, введите ваше имя и телефон',
      'checkout_success': 'Успешно оформлено!',
      'checkout_error': 'Произошла ошибка. Пожалуйста, попробуйте еще раз.',
      'confirm_order': 'Подтвердить заказ',
      'delivery_promo_free': 'Купите еще на %s %s и получите бесплатную доставку!',
      'delivery_promo_tier': 'Купите еще на %s %s и снизьте стоимость доставки до %s %s!',

      // --- Login & SMS Screens ---
      'login_title': 'Вход в систему',
      'login_desc_phone': 'Для входа в приложение введите свой номер телефона и подтвердите по SMS-коду',
      'login_desc_full': 'Для полноценного использования приложения и совершения покупок введите свое полное имя и номер телефона',
      'login_name_label': 'Имя и фамилия',
      'login_phone_label': 'Номер телефона',
      'please_enter_name': 'Пожалуйста, введите свое имя',
      'please_enter_phone_full': 'Введите номер телефона полностью',
      'phone_exists_error': 'Этот номер уже существует в системе. Пожалуйста, нажмите "Я уже в системе".',
      'phone_not_exists_error': 'Этого номера нет в системе. Пожалуйста, зарегистрируйтесь.',
      'get_code_button': 'Получить код',
      'create_new_account': 'Создать новый аккаунт',
      'already_in_system': 'Я уже в системе',
      'sms_title': 'Подтверждение',
      'sms_desc': 'Код подтверждения отправлен на введенный вами номер. Пожалуйста, введите код.',

      // --- Onboarding Screen ---
      'onboarding_title_1': 'Все необходимые вещи',
      'onboarding_desc_1': 'Все от продуктов до товаров для дома в одном приложении',
      'onboarding_title_2': 'Быстрая доставка',
      'onboarding_desc_2': 'Ваш заказ будет доставлен быстро и надежно прямо к вашей двери',
      'onboarding_title_3': 'Отличные скидки',
      'onboarding_desc_3': 'Каждый день новые акции и скидки специально для вас',
      'onboarding_start': 'Начать',
      'onboarding_next': 'Далее',

      // --- Checkout & Orders ---
      'chiqish_tasdiq': 'Вы действительно хотите выйти из аккаунта?',
      'bekor_qilish': 'Отмена',
      'chiqish': 'Выйти',
      'mening_manzilim': 'Мой адрес',
      'ilova_tili': 'Язык приложения',
      'tungi_rejim': 'Ночной режим',
      'qollab_quvvatlash': 'Поддержка',
      'ilova_haqida': 'Об приложении',
      'ilova_tilini_tanlang': 'Выберите язык приложения',
      'savatingiz_bosh': 'Ваша корзина пуста',
      'xaridni_boshlash': 'Начать покупки',
      'xaridga_qoshilgan': 'Добавлено к покупке',
      'keyinchalikka_qoldirildi': 'Отложено на потом',
      'jami_summa': 'Общая сумма:',
      'savatda_yetarli_mahsulot_yoq': 'Недостаточно товаров в корзине!',
      'rasmiylashtirish': 'Оформить заказ',
      'hozircha_buyurtmalar_yoq': 'Пока нет заказов',
      'sana': 'Дата:',
      'buyurtma_id': 'ID заказа:',
      'jami': 'ИТОГО:',
      'yangi_tab': 'Новые',
      'yetkazilgan_tab': 'Доставлено',
      'hammasi_tab': 'Все',
      'jarayonda': 'В процессе',
      'yetkazilgan': 'Доставлено',
      'mahsulot': 'товаров',
      'buyurtma': 'Заказ',
      'buyurtma_jarayoni': 'Процесс заказа',
      'qabul_kutilmoqda': 'Ожидает принятия',
      'tayyorlanmoqda': 'Готовится',
      'yetkazilmoqda': 'В пути',
      'yetkazildi': 'Доставлено',
      'mijoz_malumotlari': 'Данные клиента',
      'fish': 'Ф.И.О:',
      'telefon': 'Телефон:',
      'manzil': 'Адрес:',
      'tolov_usuli': 'Способ оплаты:',
      'xarid_qilingan_mahsulotlar': 'Купленные товары',
      'dona': 'шт',
      'tasdiqlash_kodi': 'Код подтверждения',
      'kuryer_ogohlantirish': 'Сообщите код курьеру при получении. Через код закрывается заказ.',
      'qidirish': 'Поиск...',
      'hech_narsa_topilmadi': 'Ничего не найдено',
      'qidiruv_tarixini_boshlang': 'Начните историю поиска',
      'qidiruv_tarixi': 'История поиска',
      'katalogdan_qidirish': 'Поиск по каталогу...',
      'bolimidan_qidirish': 'поиск в категории',
      'hozircha_malumot_yoq': 'Пока нет данных',
      'kategoriyalar': 'Категории',
      'yangi_maxsulotlar': 'Новые товары',
      'maxsulotlar': 'Все товары',
      'natija': 'Результаты',
      'you_might_like': 'Вам может понравиться',
      'qulay_tezkor': 'Удобно, быстро и недорого',
      'tilni_ozgartirish': 'Изменить язык',
      'kunduzgi_rejim': 'Светлая тема',
      'mahsulot_toifa_qidirish': 'Поиск товаров и категорий',
      'aksiya_1': 'Акция 1',
      'aksiya_1_subtitle': '-50% Скидка',
      'yangi_maxsulotlar_subtitle': "Попробуйте первыми",
      'bepul_yetkazish': 'Бесплатная доставка',
      'bepul_yetkazish_subtitle': "Для покупок от 100 000 сум",
      'Chegirma': 'Скидки',
      'Oziq-ovqat': 'Продукты',
      'Ichimliklar': 'Напитки',
      'Shirinliklar': 'Сладости',
      'Mevalar': 'Фрукты',
      'Sabzavotlar': 'Овощи',
      "Go'sht": "Мясо",
      'Sut mahsulotilari': 'Молочные продукты',
      'Non va un': 'Хлеб и мука',
      'Maishiy kimyo': 'Бытовая химия',
      'Bolalar oziq-ovqati': 'Детское питание',
      "Go'zallik": "Красота",
      'Uy hayvonlari': 'Для животных',
      'buyurtma_no': 'Заказ №:',
      'buyurtma_id_title': 'ID заказа:',
      'yuboruvchi': 'Отправитель:',
      'oluvchi': 'Получатель:',
      'mahsulotlar_soni': 'Кол-во товаров:',
      'telefon_raqami': 'Номер телефона:',
      'som': 'сум',
      'ta_dona': 'шт',
      'mahsulotni_korish': 'Посмотреть товар',
      'buyurtma_raq_id': 'Номер заказа / ID:',
      'kuryerga_tolov': 'Курьеру',
      'sana_va_vaqt': 'Дата и время:',
      'kuryerga_izoh': 'Комментарий курьеру:',
      'order_delivered_title': 'Заказ доставлен',
      'order_cancelled_title': 'Заказ отменен',
      'order_process_title': 'На каком этапе мой заказ:',
      'order_cancelled': 'Заказ отменен',
      'error': 'Ошибка',
      'cancel_order_btn': 'Отменить заказ',
      'cancel_warning_desc': "Вы можете без проблем отменить свой заказ до того, как его примут или пока он готовится. Но как только заказ станет 'Готов' и передан курьеру, отмена невозможна!",
      'Qabul qilingan': 'Принят',
      'Qabul qilish kutilmoqda': 'Ожидает принятия',
      'Qabul qilinishi kutilmoqda': 'Ожидается принятие',
      'Tayyor': 'Готов',
      'Tayyorlanmoqda': 'Готовится',
      "Yo'lda": 'В пути',
      'Kuryer kutilmoqda': 'Ожидается курьер',
      'Kuryerga berildi': 'Передан курьеру',
      'Yetkazildi': 'Доставлено',
      'chegirmalik_badge': 'Со скидкой',
      'cancelled_badge': 'Отменен',
      'hisob_kitob': 'Расчет',
      'umumiy_mahsulot_narxi': 'Общая стоимость:',
      'yetkazib_berish_title': 'Доставка:',
      'bepul': 'Бесплатно',
      'promo_kod_chegirma': 'Промокод (Скидка):',
      'yoq': 'Нет',
      'mahsulotlar': 'Товары',
      'buyurtma_tafsilotlari': 'Детали заказа',
      'sevimlilar': 'Избранное',
      'sevimlilar_bosh': 'Список избранного пуст',
      'bizning_dokonlarimiz': "Наши магазины",
      'announcements': 'Объявления',
      'no_announcements': 'Пока нет объявлений',
      'january': 'Января',
      'february': 'Февраля',
      'march': 'Марта',
      'april': 'Апреля',
      'may_month': 'Мая',
      'june': 'Июня',
      'july': 'Июля',
      'august': 'Августа',
      'september': 'Сентября',
      'october': 'Октября',
      'november': 'Ноября',
      'december': 'Декабря',
    },
    'en': {
      'savatga': 'To Cart',
      'otish': 'Go',
      'savatga_qoshish': 'Add to Cart',
      'savatga_qoshildi': 'Added to cart',
      'narxi': 'PRICE',
      'malumot': 'Info',
      'asosiy': 'Home',
      'katalog': 'Catalog',
      'savat': 'Cart',
      'buyurtmalarim': 'My Orders',
      'profil': 'Profile',
      'chegirma': 'DISCOUNT',
      'tasdiqlash': 'Confirm',
      'buyurtma_berish': 'Checkout',
      'tilni_tanlang': 'Select Language',
      'davom_etish': 'Continue',
      'tizimdan_chiqish': 'Log Out',

      // --- Login & SMS Screens ---
      'login_title': 'Log In',
      'login_desc_phone': 'To log into the app, enter your phone number and confirm via SMS code',
      'login_desc_full': 'To fully use the app and make purchases, enter your full name and phone number',
      'login_name_label': 'Name and Surname',
      'login_phone_label': 'Phone Number',
      'please_enter_name': 'Please enter your name',
      'please_enter_phone_full': 'Please enter your full phone number',
      'phone_exists_error': 'This number already exists in the system. Please click "Already in system".',
      'phone_not_exists_error': 'This number does not exist in the system. Please register.',
      'get_code_button': 'Get Code',
      'create_new_account': 'Create new account',
      'already_in_system': 'Already in system',
      'sms_title': 'Verification',
      'sms_desc': 'A verification code has been sent to the number you entered. Please enter the code.',

      // --- Onboarding Screen ---
      'onboarding_title_1': 'All necessary things',
      'onboarding_desc_1': 'Everything from groceries to household items in one app',
      'onboarding_title_2': 'Fast Delivery',
      'onboarding_desc_2': 'Your order will be delivered quickly and reliably to your door',
      'onboarding_title_3': 'Great Discounts',
      'onboarding_desc_3': 'New promotions and discounts every day just for you',
      'onboarding_start': 'Start',
      'onboarding_next': 'Next',

      // --- About Screen ---
      'versiya': 'Version',
      'about_desc': "The fastest and most reliable online supermarket! We deliver the best quality products to your home in an instant.",
      'faq_title': "Frequently Asked Questions",
      'faq_q1': "How long does delivery take?",
      'faq_a1': "True to its name, Raketa Market will deliver your order in 15-30 minutes.",
      'faq_q2': "What payment methods are available?",
      'faq_a2': "You can easily pay in cash, or directly using uzcard or humo cards.",
      'faq_q3': "Can I cancel my order?",
      'faq_a3': "You can cancel your order easily before it goes to the delivery stage.",
      'faq_q4': "How can I change profile details?",
      'faq_a4': "Go to the profile section, and under 'Personal Information' you can edit your name, gender and other details.",
      'faq_q5': "What happens if a product is defective?",
      'faq_a5': "We guarantee quality. If you do not like the quality of the product, you can reject it via the courier, and your money will not be charged.",

      // --- Support & Profile Edit ---
      'support_title': "Support Base",
      'support_question': "How do you want to contact us?",
      'support_desc': "If you have questions or suggestions, write or call us.",
      'support_cancel': "Cancel",
      'via_telegram': "Via Telegram",
      'telegram_desc': "Quick messaging and response",
      'send_msg': "Send Message",
      'via_phone': "Make a Call",
      'phone_desc': "Contact the call center",
      'redirecting': "Redirecting...",
      'personal_info': "Personal Information",
      'name_label': "Address name",
      'name_hint': "Enter your name",
      'surname_label': "Surname",
      'surname_hint': "Enter your surname",
      'dob_label': "Date of Birth",
      'gender_label': "Gender",
      'male': "Male",
      'female': "Female",
      'phone_label': "Phone Number",
      'email_label': "E-mail Address",
      'email_hint': "example@mail.com",
      'save_button': "Save",
      'del_acc': "Delete Account Permanently",
      'del_acc_title': "Delete Account",
      'del_acc_desc': "Are you sure you want to permanently delete your account? All your data and history will be permanently erased.",
      'del_acc_btn': "Delete",
      'confirm_number': "Confirm Number",
      'enter_sms': "Enter the SMS code sent to your new number",
      'verify_btn': "Verify",
      'data_saved': "Data saved successfully!",
      'acc_deleted': "Account deleted successfully",

      // --- Addresses Screen ---
      'my_address': 'My Address',
      'region_select_title': 'Select Region',
      'district_select_title': 'Select District (City)',
      'your_region': 'Your Region:',
      'select_region_hint': 'Select Region',
      'add_address_prompt': "First select a region \nto enter your address",
      'sorry': 'Sorry! 😔',
      'no_service': "Our service is not available in the selected region yet. But we will get there soon!",
      'address_details': 'Address details:',
      'region_label': 'Region',
      'district_label': 'District',
      'street_label': "Street",
      'house_label': 'House',
      'house_hint': 'Example: House 45, Apartment 12',
      'pick_map': 'Select from Map',
      'fill_all': "Please fill in all fields",
      'address_saved': 'Your address has been saved!',
      'map_open_warning': 'Map location selection will open',
      'add_new_address': "Add New Address",
      'address_title_label': "Address Title (e.g., Home, Work)",
      'address_title_hint': "Give a name to the address",
      'set_as_default': "Set as default address",
      'delete_address_confirm': "Are you sure you want to delete this address?",
      'no_addresses_yet': "No addresses yet. Add a new one!",
      'default_label': "Default",
      'save_address': "Save Address",
      'select_within': "Please select within",
      'area': "area",
      'loading': "Loading...",
      'coordinates': "Coordinates",
      'search_on_map': "Select address on map",
      'region_not_active': "We are not here yet",
      'gps_disabled': "GPS disabled",
      'location_permission_denied': "Location permission denied",
      'unable_to_determine_location': "Unable to determine location",
      'understand': "Understand",
      'get_directions': "Get directions",
      'pickup_at_main_store': "Pickup (Main store)",
      'promo_info_title': 'Promo Code Information',
      'promo_eligibility_note': 'Promo code only applies to non-discounted (non-yellow price) items.',
      'promo_info_text_main': 'When applying a promo code to delivery or products, the amount of products already discounted is not counted.',
      'promo_info_text_important': 'Important: PROMO CODE for products only applies to items that do not already have a store discount (non-discounted items). There must be enough non-discounted items in your cart.',
      'view_products_list': 'View products list',
      'discounted_products': "Discounted Products",
      'non_discounted_products': "Non-discounted Products",

      // --- Checkout Screen Details ---
      'checkout': 'Checkout',
      'contact_info': 'Contact Information',
      'full_name': 'Full Name',
      'phone_number': 'Phone Number',
      'receive_method': 'Receive Method',
      'delivery': 'Delivery',
      'pickup': 'Pickup (Coming soon)',
      'your_address': 'Your Address',
      'searching_address': 'Searching address...',
      'unknown_area': 'Unknown area',
      'cannot_determine_address': 'Cannot determine address',
      'connection_error': 'Connection error',
      'courier_desc': 'Description for courier',
      'courier_desc_hint': 'Example: house number, entrance, etc.',
      'store_address': 'Store Address',
      'raketa_main_branch': 'Raketa Market (Main Branch)',
      'store_address_detail': 'Tashkent city, Yunusabad district, 4th block, house 12',
      'start_routing': 'Start Route',
      'payment_type': 'Payment Type',
      'cash_payment': 'Cash',
      'card_payment': 'Card',
      'coming_soon': 'Coming Soon',
      'card_number': 'Card Number',
      'expire_date': 'Exp Date',
      'charge_payment': 'Charge Payment',
      'promo_code': 'Promo Code',
      'enter_promo': 'Enter promo code',
      'apply': 'Apply',
      'promo_applied': 'Promo code applied!',
      'wrong_promo': 'Invalid promo code',
      'promo_not_found': 'Promo code not found or expired',
      'promo_missing_amount_error': 'Add another %s worth of non-discounted items',
      'promo_min_amount_error': 'Non-discounted total must be at least %s som',
      'promo_total_limit_reached': 'Sorry, promo code limit has been reached',
      'promo_user_limit_reached': 'You have already used this promo code',
      'promo_eligible_error': 'Sorry, this promo code only applies to non-discounted products',
      'promo_system_error': 'System error occurred. Please try again later',
      'chegirma_berildi': 'You received a discount of %s UZS',
      'products_label': 'Products:',
      'delivery_fee': 'Delivery:',
      'free': 'Free',
      'discount_label': 'Discount:',
      'total_amount_checkout': 'Total Amount:',
      'fill_name_phone': 'Please enter your name and phone',
      'checkout_success': 'Successfully checked out!',
      'checkout_error': 'An error occurred. Please try again.',
      'confirm_order': 'Confirm Order',
      'delivery_promo_free': 'Buy for %s %s more and get free delivery!',
      'delivery_promo_tier': 'Buy for %s %s more and lower the delivery price to %s %s!',

      // --- Checkout & Orders ---
      'chiqish_tasdiq': 'Are you sure you want to log out?',
      'bekor_qilish': 'Cancel',
      'chiqish': 'Logout',
      'mening_manzilim': 'My Address',
      'ilova_tili': 'App Language',
      'tungi_rejim': 'Dark Mode',
      'qollab_quvvatlash': 'Support',
      'ilova_haqida': 'About App',
      'ilova_tilini_tanlang': 'Select app language',
      'savatingiz_bosh': 'Your cart is empty',
      'xaridni_boshlash': 'Start shopping',
      'xaridga_qoshilgan': 'Added to purchase',
      'keyinchalikka_qoldirildi': 'Saved for later',
      'jami_summa': 'Total amount:',
      'savatda_yetarli_mahsulot_yoq': 'Not enough products in cart!',
      'rasmiylashtirish': 'Checkout',
      'hozircha_buyurtmalar_yoq': 'No orders yet',
      'sana': 'Date:',
      'buyurtma_id': 'Order ID:',
      'jami': 'TOTAL:',
      'yangi_tab': 'New',
      'yetkazilgan_tab': 'Delivered',
      'hammasi_tab': 'All',
      'jarayonda': 'Processing',
      'yetkazilgan': 'Delivered',
      'mahsulot': 'items',
      'buyurtma': 'Order',
      'buyurtma_jarayoni': 'Order Process',
      'qabul_kutilmoqda': 'Awaiting Acceptance',
      'tayyorlanmoqda': 'Preparing',
      'yetkazilmoqda': 'On the way',
      'yetkazildi': 'Delivered',
      'mijoz_malumotlari': 'Customer Details',
      'fish': 'Full Name:',
      'telefon': 'Phone:',
      'manzil': 'Address:',
      'tolov_usuli': 'Payment Method:',
      'xarid_qilingan_mahsulotlar': 'Purchased Items',
      'dona': 'pcs',
      'tasdiqlash_kodi': 'Confirmation Code',
      'kuryer_ogohlantirish': 'Provide the code to the courier upon delivery to close the order.',
      'qidirish': 'Search...',
      'hech_narsa_topilmadi': 'Nothing found',
      'qidiruv_tarixini_boshlang': 'Start search history',
      'qidiruv_tarixi': 'Search History',
      'katalogdan_qidirish': 'Search in catalog...',
      'bolimidan_qidirish': 'search in category',
      'hozircha_malumot_yoq': 'No data yet',
      'kategoriyalar': 'Categories',
      'yangi_maxsulotlar': 'New Products',
      'maxsulotlar': 'All Products',
      'natija': 'Results',
      'you_might_like': 'You might like',
      'qulay_tezkor': 'Convenient, fast and affordable',
      'tilni_ozgartirish': 'Change language',
      'kunduzgi_rejim': 'Light Mode',
      'mahsulot_toifa_qidirish': 'Search for products and categories',
      'aksiya_1': 'Promotion 1',
      'aksiya_1_subtitle': '-50% Discount',
      'yangi_maxsulotlar_subtitle': "Be the first to taste",
      'bepul_yetkazish': 'Free Delivery',
      'bepul_yetkazish_subtitle': "For purchases of 100,000 UZS and more",
      'Chegirma': 'Discounts',
      'Oziq-ovqat': 'Groceries',
      'Ichimliklar': 'Beverages',
      'Shirinliklar': 'Sweets',
      'Mevalar': 'Fruits',
      'Sabzavotlar': 'Vegetables',
      "Go'sht": "Meat",
      'Sut mahsulotilari': 'Dairy',
      'Non va un': 'Bread & Flour',
      'Maishiy kimyo': 'Household Chemicals',
      'Bolalar oziq-ovqati': 'Baby Food',
      "Go'zallik": "Beauty",
      'Uy hayvonlari': 'Pets',
      'buyurtma_no': 'Order No:',
      'buyurtma_id_title': 'Order ID:',
      'yuboruvchi': 'Sender:',
      'oluvchi': 'Receiver:',
      'mahsulotlar_soni': 'Number of items:',
      'telefon_raqami': 'Phone Number:',
      'som': 'UZS',
      'ta_dona': 'pcs',
      'mahsulotni_korish': 'View Product',
      'buyurtma_raq_id': 'Order Number / ID:',
      'kuryerga_tolov': 'To Courier',
      'sana_va_vaqt': 'Date and Time:',
      'kuryerga_izoh': 'Courier note:',
      'order_delivered_title': 'Order Delivered',
      'order_cancelled_title': 'Order Canceled',
      'order_process_title': 'What stage is my order at:',
      'announcements': 'Announcements',
      'no_announcements': 'No announcements yet',
      'january': 'January',
      'february': 'February',
      'march': 'March',
      'april': 'April',
      'may_month': 'May',
      'june': 'June',
      'july': 'July',
      'august': 'August',
      'september': 'September',
      'october': 'October',
      'november': 'November',
      'december': 'December',
      'order_cancelled': 'Order canceled',
      'error': 'Error',
      'cancel_order_btn': 'Cancel Order',
      'cancel_warning_desc': "You can easily cancel your order before it is accepted and during preparation. But once the order is 'Ready' and given to the courier, it cannot be canceled!",
      'Qabul qilingan': 'Accepted',
      'Qabul qilish kutilmoqda': 'Awaiting Acceptance',
      'Qabul qilinishi kutilmoqda': 'Pending Acceptance',
      'Tayyor': 'Ready',
      'Tayyorlanmoqda': 'Preparing',
      "Yo'lda": 'On the way',
      'Kuryer kutilmoqda': 'Awaiting Courier',
      'Kuryerga berildi': 'Given to Courier',
      'Yetkazildi': 'Delivered',
      'chegirmalik_badge': 'Discounted',
      'cancelled_badge': 'Cancelled',
      'hisob_kitob': 'Calculation',
      'umumiy_mahsulot_narxi': 'Total product price:',
      'yetkazib_berish_title': 'Delivery:',
      'bepul': 'Free',
      'promo_kod_chegirma': 'Promo code (Discount):',
      'yoq': 'No',
      'mahsulotlar': 'Products',
      'buyurtma_tafsilotlari': 'Order Details',
      'sevimlilar': 'Favorites',
      'sevimlilar_bosh': 'Your favorites list is empty',
      'bizning_dokonlarimiz': "Our Stores",
    }
  };

  Future<void> loadLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    final savedCode = prefs.getString('language_code');
    if (savedCode != null && _localizedStrings.containsKey(savedCode)) {
      _currentLanguage = savedCode;
      notifyListeners();
    }
  }

  Future<void> changeLanguage(String code) async {
    if (_localizedStrings.containsKey(code)) {
      _currentLanguage = code;
      notifyListeners(); // <--- Darxol UI ni yangilash
      try {
        final prefs = await SharedPreferences.getInstance();
        await prefs.setString('language_code', code);
      } catch (e) {
        debugPrint('LangPrefs error: $e');
      }
    }
  }

  String translate(String key) {
    return _localizedStrings[_currentLanguage]?[key] ?? key;
  }
}
